### ISSUE TITLE
Is there a documentation on how to use this?

### ISSUE THREAD

**Issue by freakeinstein** [microsoft/tf-gnn-samples#5]
Hi, I'm looking into this repo and wondering small details such as,
* format of training data
* what problems it can solve
* how to use it after training and testing
* How to generate embeddings?

Is there any documentation / article hosted?

**Comment by MokoSan** [comment]
Hi, I have just started the process of deep diving into the code here and here my answers:

**format of training data**
The training set that got the ball rolling for me is mentioned [here](https://github.com/microsoft/tf-gnn-samples#ppi). Specifically, [this](https://s3.us-east-2.amazonaws.com/dgl.ai/dataset/ppi.zip) link should get you the data to start running the examples.

**what problems it can solve**
The problems to solve are defined by __tasks__. For example, the one I am exclusively taking a look a at is the ``VarMisuseTask`` whose details can be found [here](https://s3.us-east-2.amazonaws.com/dgl.ai/dataset/ppi.zip). What really helped me here to understanding what the tasks entail was to read the associated white paper: https://arxiv.org/pdf/1711.00740.pdf. 

**How to use it after training and testing**
Once you run the model and have finished testing it, the model is persisted locally under a freshly created ``trained_models`` directory that can be used for further development. Again, the models are coupled to a task at hand, so that consideration should be made. 

**How to generate embeddings?**
At least for the VarMisuseTask, the initial embeddings are available directly from the data set. I have found the following repo that could help with some of the embedding generation based on the translation unit at hand: https://github.com/microsoft/dpu-utils/tree/master/dotnet - will be experimenting with this, myself. 

Hopefully this helps to get the ball rolling - been working towards understanding all the code, myself and still a novice here but this space is super super exciting!

Best,
MokoSan

**Comment by mmjb** [comment]
@freakeinstein, I'm not quite sure what you are looking for beyond the information in the README:
* https://github.com/microsoft/tf-gnn-samples#tasks covers both which problems the provided code can learn to solve, as well as what data it consumes. As this is a library of fairly generic nature, this just describes three tasks that are implemented. Their raw input data format varies wildly, and it makes most sense to look at the implementation of the different datasets (in `tasks/`).
 If you are asking about the _internal_ format of data, have a look at the docstrings in https://github.com/microsoft/tf-gnn-samples/blob/master/tasks/sparse_graph_task.py#L107-211, which describe this.
* No code is provided to use this after batched train/test. This is because this is primarily a library of reusable code; for deployment, it would be easiest to adapt the existing `test.py` to your scenario.
* As the example tasks all assume a supervised setting, (graph) embeddings are only produced as intermediate results; these are placed in `ops['final_node_representations']` in https://github.com/microsoft/tf-gnn-samples/blob/master/models/sparse_graph_model.py#L162 and then consumed differently in the different tasks.

**Comment by mmjb** [comment]
As there was no followup on this to clarify the questions, I'm closing this issue now.
